- user-service/build.gradle.kts
- user-service/src/main/java/kr/mafoo/user/annotation/RequestMemberId.java
- user-service/src/main/java/kr/mafoo/user/api/MeApi.java
- user-service/src/main/java/kr/mafoo/user/config/MemberIdParameterResolver.java
- user-service/src/main/java/kr/mafoo/user/config/RequestMemberId.java
- user-service/src/main/java/kr/mafoo/user/config/WebExceptionHandler.java
- user-service/src/main/java/kr/mafoo/user/config/WebFluxConfig.java
- user-service/src/main/java/kr/mafoo/user/controller/MeController.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/ErrorResponse.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/MemberResponse.java
- user-service/src/main/java/kr/mafoo/user/domain/MemberEntity.java
- user-service/src/main/java/kr/mafoo/user/exception/DomainException.java
- user-service/src/main/java/kr/mafoo/user/exception/ErrorCode.java
- user-service/src/main/java/kr/mafoo/user/exception/MemberNotFoundException.java
- user-service/src/main/java/kr/mafoo/user/repository/MemberRepository.java
- user-service/src/main/java/kr/mafoo/user/service/MemberService.java
- user-service/src/main/resources/application.yaml
제가 다음주에 바쁜 관계로 미리미리 치고있슴다
- 사용자 조회 API (GET /v1/me) 구현
- 사용자 탈퇴 API (POST /v1/me/quit) 구현
화이팅 해봅시다 하나둘 화이팅!
Closes #5
> feat: 사용자 조회, 탈퇴 API 구현

- user-service/build.gradle.kts
- user-service/src/main/java/kr/mafoo/user/UserServiceApplication.java
- user-service/src/main/java/kr/mafoo/user/config/JacksonSerializer.java
- user-service/src/main/java/kr/mafoo/user/config/WebFluxConfig.java
- user-service/src/main/java/kr/mafoo/user/config/properties/KakaoOAuthProperties.java
- user-service/src/main/java/kr/mafoo/user/controller/AuthController.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/KakaoLoginInfo.java
- user-service/src/main/java/kr/mafoo/user/domain/AuthToken.java
- user-service/src/main/java/kr/mafoo/user/domain/MemberEntity.java
- user-service/src/main/java/kr/mafoo/user/domain/SocialMemberEntity.java
- user-service/src/main/java/kr/mafoo/user/domain/SocialMemberEntityKey.java
- user-service/src/main/java/kr/mafoo/user/enums/IdentityProvider.java
- user-service/src/main/java/kr/mafoo/user/exception/ErrorCode.java
- user-service/src/main/java/kr/mafoo/user/exception/InvalidTokenException.java
- user-service/src/main/java/kr/mafoo/user/exception/KakaoLoginFailedException.java
- user-service/src/main/java/kr/mafoo/user/exception/TokenExpiredException.java
- user-service/src/main/java/kr/mafoo/user/exception/TokenTypeMismatchException.java
- user-service/src/main/java/kr/mafoo/user/repository/SocialMemberRepository.java
- user-service/src/main/java/kr/mafoo/user/service/AuthService.java
- user-service/src/main/java/kr/mafoo/user/service/JWTTokenService.java
- user-service/src/main/java/kr/mafoo/user/service/MemberService.java
- user-service/src/main/java/kr/mafoo/user/util/IdGenerator.java
- user-service/src/main/resources/application.yaml
- user-service/src/main/resources/db/migration/V1__init.sql
카카오 로그인 API 구현
- 카카오 로그인 API 구현
- 에 필요한 토큰 발급 API 구현
- 및 Refresh Token 발급 API 구현
화이팅합시당
Closes #7
> feat: 카카오 로그인 구현

- photo-service/build.gradle.kts
- photo-service/src/main/java/kr/mafoo/photo/config/NcpConfig.java
- photo-service/src/main/java/kr/mafoo/photo/config/WebFluxConfig.java
- photo-service/src/main/java/kr/mafoo/photo/controller/PhotoController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/response/PhotoResponse.java
- photo-service/src/main/java/kr/mafoo/photo/domain/BrandType.java
- photo-service/src/main/java/kr/mafoo/photo/domain/PhotoEntity.java
- photo-service/src/main/java/kr/mafoo/photo/exception/ErrorCode.java
- photo-service/src/main/java/kr/mafoo/photo/exception/PhotoBrandNotExistsException.java
- photo-service/src/main/java/kr/mafoo/photo/exception/PhotoQrUrlExpiredException.java
- photo-service/src/main/java/kr/mafoo/photo/exception/RedirectUriNotFoundException.java
- photo-service/src/main/java/kr/mafoo/photo/service/ObjectStorageService.java
- photo-service/src/main/java/kr/mafoo/photo/service/PhotoService.java
- photo-service/src/main/java/kr/mafoo/photo/service/QrService.java
- photo-service/src/main/java/kr/mafoo/photo/service/dto/FileDto.java
- photo-service/src/main/resources/application.yaml
- photo-service/src/main/resources/db/migration/V3__addBrandInPhotoTable.sql
사진 저장 API를 구현했습니다
- POST /v1/photos
~나머지 브랜드는 유효한 QR로 테스트 한 번씩만 해보고 추가하겠습니다!~ - 추가 완료!
Closes #12
> feat: 사진 저장 API 구현

- photo-service/src/main/java/kr/mafoo/photo/api/AlbumApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/AlbumController.java
- photo-service/src/main/java/kr/mafoo/photo/service/AlbumService.java
사진 단건 조회 API를 구현했습니다
- GET /v1/albums/{albumId}
앨범 생성 API가 ownerMemberId 이슈로 작동하지 않아서 확인 후 리뷰 요청드릴게요...!
Closes #15
> feat: 사진 단건 조회 API 구현

- user-service/build.gradle.kts
- user-service/src/main/java/kr/mafoo/user/api/AuthApi.java
- user-service/src/main/java/kr/mafoo/user/api/MeApi.java
- user-service/src/main/java/kr/mafoo/user/config/WebExceptionHandler.java
- user-service/src/main/java/kr/mafoo/user/exception/ErrorCode.java
요청 Validation으로 불필요한 500 에러를 방지하였습니다.
사진 서비스와 달리 이쪽엔 아직 검증할만한 필드나 프로퍼티가 없었습니다.
- 사진 서비스 API 요청 검증
- 검증 실패 예외 핸들링
감사합니다
Closes #18
> feat: 유저 서비스 요청 Validation 작업

- photo-service/build.gradle.kts
- photo-service/src/main/java/kr/mafoo/photo/annotation/MatchEnum.java
- photo-service/src/main/java/kr/mafoo/photo/annotation/ULID.java
- photo-service/src/main/java/kr/mafoo/photo/api/AlbumApi.java
- photo-service/src/main/java/kr/mafoo/photo/api/PhotoApi.java
- photo-service/src/main/java/kr/mafoo/photo/config/WebExceptionHandler.java
- photo-service/src/main/java/kr/mafoo/photo/controller/AlbumController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/AlbumCreateRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/AlbumUpdateRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/PhotoCreateRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/PhotoUpdateAlbumIdRequest.java
- photo-service/src/main/java/kr/mafoo/photo/exception/ErrorCode.java
요청 Validation으로 불필요한 500 에러를 방지하였습니다.
- 사진 서비스 API 요청 검증
- 검증 실패 예외 핸들링
감사합니다
Closes #17
> feat: 사진 서비스 요청 Validation 작업

- user-service/src/main/java/kr/mafoo/user/controller/dto/response/KakaoLoginInfo.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/MemberResponse.java
- user-service/src/main/java/kr/mafoo/user/domain/MemberEntity.java
- user-service/src/main/java/kr/mafoo/user/service/AuthService.java
- user-service/src/main/java/kr/mafoo/user/service/MemberService.java
- user-service/src/main/resources/db/migration/V2__add_profile_img_url_field.sql
민수님의 부탁입니다
- Member에 프로필 이미지 필드 추가
- 카카오 회원가입시 이미지 연동
Closes #22
> feat: 프로필 이미지 기능 추가 및 카카오 연동

- user-service/build.gradle.kts
- user-service/src/main/java/kr/mafoo/user/api/AuthApi.java
- user-service/src/main/java/kr/mafoo/user/config/properties/AppleOAuthProperties.java
- user-service/src/main/java/kr/mafoo/user/controller/AuthController.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/request/AppleLoginRequest.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/AppleKeyListResponse.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/AppleKeyResponse.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/response/AppleLoginInfo.java
- user-service/src/main/java/kr/mafoo/user/enums/IdentityProvider.java
- user-service/src/main/java/kr/mafoo/user/service/AuthService.java
- user-service/src/main/java/kr/mafoo/user/util/NicknameGenerator.java
- user-service/src/main/resources/application.yaml
곧 애플 로그인이 생깁니다
애플 로그인 기능구현
ㅎㅇㅌ
Closes #35
> feat: 애플 로그인 서버 기능 구현

- api-gateway/src/main/resources/application-prod.yaml
- api-gateway/src/main/resources/application.yaml
- photo-service/src/main/resources/application-prod.yaml
- photo-service/src/main/resources/application.yaml
- user-service/src/main/resources/application-prod.yaml
- user-service/src/main/resources/application.yaml
사진 추가 API 비로그인 상태에서도 호출 가능토록
+ 하는김에 zipkin 관련 오류도 해결
- 사진 추가 API 비로그인 상태에서 호출 가능하도록 게이트웨이 설정 변경
- 프로덕션용 application.yaml 추가
- zipkin 기본값 비활성화로 변경
< 여기에 하고싶은 말 >
Closes #45
> feat: 사진 등록 API 비로그인 상태에서도 호출 가능

- user-service/src/main/java/kr/mafoo/user/controller/AuthController.java
- user-service/src/main/java/kr/mafoo/user/controller/dto/request/KakaoLoginRequest.java
- user-service/src/main/java/kr/mafoo/user/service/AuthService.java
프론트와 더 원활한 작업 위함
카카오 로그인 Redirect URL 고도화
아 어제 말한 PR 관련 나누고싶던 얘기가 제목 얘기였어요. 제목 이런 형태 괜찮나요?
[JIRA 티켓 링크](https://3spinachpasta.atlassian.net/browse/MAFOO-25)
> [MAFOO-25] feat: 카카오 로그인 Redirect URL 고도화

- photo-service/src/main/java/kr/mafoo/photo/domain/BrandType.java
- photo-service/src/main/java/kr/mafoo/photo/service/QrService.java
- photo-service/src/main/java/kr/mafoo/photo/service/vendors/MonoMansionQrVendor.java
- photo-service/src/main/java/kr/mafoo/photo/service/vendors/PhotoSignatureQrVendor.java
- photo-service/src/main/java/kr/mafoo/photo/service/vendors/PicDotQrVendor.java
- photo-service/src/main/java/kr/mafoo/photo/util/WebClientUtil.java
브랜드가 추가되었어요
- 모노맨션
- 포토시그니쳐
- PicDot
ㅎㅇㅌ
https://3spinachpasta.atlassian.net/browse/MAFOO-46?atlOrigin=eyJpIjoiN2U4YTA0MDQxZmY4NDc0Y2EwMjRkNTAxNDM1YTFjZjMiLCJwIjoiaiJ9
> [MAFOO-46] feat: 여러 브랜드 추가

- photo-service/src/main/java/kr/mafoo/photo/controller/PhotoController.java
- photo-service/src/main/java/kr/mafoo/photo/domain/BrandType.java
- photo-service/src/main/java/kr/mafoo/photo/service/QrService.java
- photo-service/src/main/java/kr/mafoo/photo/service/vendors/MafooQrVendor.java
테스트를 위한 qr로 이미지 발행
- MAFOO 벤더 추가
안녕하세요?
https://3spinachpasta.atlassian.net/browse/MAFOO-58
> [MAFOO-58] feat: 마푸 테스트용 QR 이미지 발급 기능 구현

- photo-service/src/main/java/kr/mafoo/photo/api/PhotoApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/PhotoController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/PhotoBulkUpdateAlbumIdRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/PhotoListUpdateAlbumIdRequest.java
- photo-service/src/main/java/kr/mafoo/photo/service/PhotoService.java
사진 n건 앨범 변경 API를 구현했어요
- PATCH /v1/photos/album
service단에서 내부 메서드를 호출하고 있는 부분이 구현해두고도 `@Transactional` 때문에 조금 불안하네요;; 이게 최선인가 고민인데 확인 부탁드려용
[MAFOO-102](https://3spinachpasta.atlassian.net/browse/MAFOO-102?atlOrigin=eyJpIjoiMWQ3Y2E0NjUyNGMxNDcxNTg1OTBlNGNjOTZkZGJjZDAiLCJwIjoiaiJ9)
> [MAFOO-102] feat: 사진 n건 앨범 변경 API 구현

- photo-service/src/main/java/kr/mafoo/photo/api/AlbumApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/AlbumController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/AlbumUpdateDisplayIndexRequest.java
- photo-service/src/main/java/kr/mafoo/photo/domain/AlbumEntity.java
- photo-service/src/main/java/kr/mafoo/photo/exception/AlbumIndexIsSameException.java
- photo-service/src/main/java/kr/mafoo/photo/exception/ErrorCode.java
- photo-service/src/main/java/kr/mafoo/photo/repository/AlbumRepository.java
- photo-service/src/main/java/kr/mafoo/photo/service/AlbumService.java
- photo-service/src/main/resources/db/migration/V6__addDisplayIndexColumnInAlbumTable.sql
앨범에 순서가 필요해요
- 순서를 설정하는 API를 추가했어요
화이팅
https://3spinachpasta.atlassian.net/browse/MAFOO-93?atlOrigin=eyJpIjoiNDRmZTY1ZjEwMmNhNGUwZGJiZmI3MDlhZWQyZDNmNzEiLCJwIjoiaiJ9
> [MAFOO-93] feat: 앨범 순서 관련 API 및 기능 추가

- photo-service/src/main/java/kr/mafoo/photo/api/PhotoApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/PhotoController.java
- photo-service/src/main/java/kr/mafoo/photo/domain/BrandType.java
- photo-service/src/main/java/kr/mafoo/photo/service/PhotoService.java
- photo-service/src/main/java/kr/mafoo/photo/service/QrService.java
파일 업로드 기능
- 파일 여러개를 직접 업로드할 수 있어요
< 여기에 하고싶은 말 >
https://3spinachpasta.atlassian.net/browse/MAFOO-115
> [MAFOO-115] feat: 파일 업로드 기능을 만들었어요

- photo-service/src/main/java/kr/mafoo/photo/config/WebFluxConfig.java
< 여기에 기능 추가 배경 >
< 여기에 기능 >
< 여기에 하고싶은 말 >
< 여기에 이슈 정보 >
> feat: 연결 시간 버퍼

- photo-service/src/main/java/kr/mafoo/photo/domain/enums/BrandType.java
포토시그니처 QR url regex 패턴 수정
- 포토시그니처 QR url regex 패턴 수정
👍
[MAFOO-193](https://3spinachpasta.atlassian.net/browse/MAFOO-193)
> [MAFOO-193] fix: 포토시그니처 QR url regex 패턴 수정

- api-gateway/src/main/resources/application.yaml
< 여기에 기능 추가 배경 >
< 여기에 기능 >
< 여기에 하고싶은 말 >
< 여기에 이슈 정보 >
> feat: add cors

- user-service/src/main/java/kr/mafoo/user/service/MemberService.java
- user-service/src/main/java/kr/mafoo/user/service/SlackService.java
사용자 가입 슬랙 알림에 serial number 필드를 추가했어요
- 사용자 가입 슬랙 알림 : serial number 추가
규원님 요청입니다~
[MAFOO-194](https://3spinachpasta.atlassian.net/browse/MAFOO-194)
> [MAFOO-194] feat: 사용자 가입 슬랙 알림에 serial number 필드 추가

- photo-service/src/main/java/kr/mafoo/photo/api/ObjectStorageApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/ObjectStorageController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/SumoneController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/ObjectStoragePreSignedUrlRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/ObjectStorageRecapPreSignedUrlRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/response/PreSignedUrlResponse.java
- photo-service/src/main/java/kr/mafoo/photo/service/ObjectStorageService.java
리캡 pre-signed url 발급 API RequestBody를 변경했어요
- fileNames -> fileCount
- albumId 추가
👍
[M25-26](https://3spinachpasta.atlassian.net/browse/M25-26)
> [M25-26] refactor: 리캡 pre-signed url 발급 API RequestBody를 변경했어요

- photo-service/src/main/java/kr/mafoo/photo/api/AlbumExportApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/AlbumExportController.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/AlbumExportCreateRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/request/AlbumExportNoteCreateRequest.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/response/AlbumExportNoteResponse.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/response/AlbumExportResponse.java
- photo-service/src/main/java/kr/mafoo/photo/controller/dto/response/ExportedAlbumResponse.java
- photo-service/src/main/java/kr/mafoo/photo/domain/AlbumExportEntity.java
- photo-service/src/main/java/kr/mafoo/photo/domain/AlbumExportLikeEntity.java
- photo-service/src/main/java/kr/mafoo/photo/domain/AlbumExportNoteEntity.java
- photo-service/src/main/java/kr/mafoo/photo/domain/enums/NoteType.java
- photo-service/src/main/java/kr/mafoo/photo/domain/key/AlbumExportLikeEntityKey.java
- photo-service/src/main/java/kr/mafoo/photo/exception/AlbumExportAlreadyExistsException.java
- photo-service/src/main/java/kr/mafoo/photo/exception/AlbumExportNotFoundException.java
- photo-service/src/main/java/kr/mafoo/photo/exception/ErrorCode.java
- photo-service/src/main/java/kr/mafoo/photo/repository/AlbumExportLikeRepository.java
- photo-service/src/main/java/kr/mafoo/photo/repository/AlbumExportNoteRepository.java
- photo-service/src/main/java/kr/mafoo/photo/repository/AlbumExportRepository.java
- photo-service/src/main/java/kr/mafoo/photo/service/AlbumExportService.java
- photo-service/src/main/java/kr/mafoo/photo/service/AlbumService.java
- photo-service/src/main/java/kr/mafoo/photo/service/MemberService.java
- photo-service/src/main/java/kr/mafoo/photo/service/PhotoService.java
- photo-service/src/main/resources/application.yaml
- photo-service/src/main/resources/db/migration/V15__createAlbumExportTable.sql
앨범 내보내기 기능을 구현해요
- 앨범 내보내기
- 앨범 내보내기 방명록
- 앨범 내보내기 좋아요
> MAFOO-195 feat: 앨범 내보내기 기능을 구현해요

- user-service/src/main/java/kr/mafoo/user/service/VariableService.java
알림 수신자 관련 변수 대응 로직을 수정했어요
- VariableService : member 관련 정보는 variable 도메인과 상관없이 포함하도록 수정
[M25-33](https://3spinachpasta.atlassian.net/browse/M25-33)
> [M25-33] refactor: 알림 수신자 관련 변수 대응 로직을 수정했어요

- user-service/src/main/java/kr/mafoo/user/controller/FcmTokenController.java
- user-service/src/main/java/kr/mafoo/user/enums/VariableDomain.java
- user-service/src/main/java/kr/mafoo/user/service/FcmTokenService.java
- user-service/src/main/java/kr/mafoo/user/service/MemberQuery.java
- user-service/src/main/java/kr/mafoo/user/service/MessageService.java
- user-service/src/main/java/kr/mafoo/user/service/NotificationService.java
- user-service/src/main/java/kr/mafoo/user/service/dto/MessageDto.java
신규 가입 시나리오 알림 전송 로직을 추가했어요
[M25-31](https://3spinachpasta.atlassian.net/browse/M25-31)
> [M25-31] feat: 신규 가입 시나리오 알림 전송 로직을 추가했어요

- photo-service/src/main/java/kr/mafoo/photo/service/RecapLambdaService.java
- photo-service/src/main/java/kr/mafoo/photo/service/SharedMemberService.java
- user-service/src/main/java/kr/mafoo/user/domain/NotificationEntity.java
- user-service/src/main/java/kr/mafoo/user/enums/VariablePlaceholder.java
- user-service/src/main/java/kr/mafoo/user/service/FcmTokenService.java
- user-service/src/main/java/kr/mafoo/user/service/MessageService.java
- user-service/src/main/java/kr/mafoo/user/service/NotificationService.java
- user-service/src/main/java/kr/mafoo/user/service/PhotoServiceClient.java
- user-service/src/main/java/kr/mafoo/user/service/VariableService.java
- user-service/src/main/java/kr/mafoo/user/service/dto/MessageDto.java
- user-service/src/main/java/kr/mafoo/user/util/MapMerger.java
- user-service/src/main/java/kr/mafoo/user/util/VariableConverter.java
공유 사용자 생성(초대) 시나리오 알림 전송 로직을 추가했어요
[M25-34](https://3spinachpasta.atlassian.net/browse/M25-34)
> [M25-34] feat: 공유 사용자 생성(초대) 시나리오 알림 전송 로직을 추가했어요

- photo-service/src/main/java/kr/mafoo/photo/api/SharedMemberApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/SharedMemberController.java
- photo-service/src/main/java/kr/mafoo/photo/service/SharedMemberCommand.java
- photo-service/src/main/java/kr/mafoo/photo/service/SharedMemberService.java
- user-service/src/main/java/kr/mafoo/user/enums/VariablePlaceholder.java
공유 사용자 초대 수락 시나리오 알림 전송 로직을 추가했어요
[M25-35](https://3spinachpasta.atlassian.net/browse/M25-35)
> [M25-34] feat: 공유 사용자 초대 수락 시나리오 알림 전송 로직을 추가했어요

- photo-service/src/main/java/kr/mafoo/photo/api/SharedMemberApi.java
- photo-service/src/main/java/kr/mafoo/photo/controller/SharedMemberController.java
- photo-service/src/main/java/kr/mafoo/photo/repository/SharedMemberRepository.java
- photo-service/src/main/java/kr/mafoo/photo/service/SharedMemberQuery.java
- photo-service/src/main/java/kr/mafoo/photo/service/SharedMemberService.java
- user-service/src/main/java/kr/mafoo/user/repository/MemberRepository.java
- user-service/src/main/java/kr/mafoo/user/service/MemberQuery.java
- user-service/src/main/java/kr/mafoo/user/service/MemberService.java
- user-service/src/main/java/kr/mafoo/user/service/PhotoServiceClient.java
- user-service/src/main/java/kr/mafoo/user/service/dto/MemberDetailDto.java
공유 앨범 대상 사용자 검색 API timeout 에러를 해결했어요
- 공유 앨범 대상 사용자 작동 방식 대폭 수정 : 사실상 처음부터 다시 구성
높은 확률로 trial 1으로 기록될지도
[M25-39](https://3spinachpasta.atlassian.net/browse/M25-39)
> [M25-39] fix: 공유 앨범 대상 사용자 검색 API timeout 에러를 해결했어요
